/*

 MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\dev\gameboy\square_fall\square.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __map_h_INCLUDE
#define __map_h_INCLUDE

#define mergezWidth 20
#define mergezHeight 18
#define mergezBank 0

extern const unsigned char mergez[];

#endif

/* End of MAP.H */
