/*

 CURSOR.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
const unsigned char cursor[] =
{
  0x02,0x00,0x7F,0x06,0xBC,0x78,0x7A,0xFC,
  0xFE,0xF4,0xFE,0xF4,0x7A,0xCC,0xB4,0x78
};

/* End of CURSOR.C */
